"""Tests for report versioning — every generated report says what produced it.

The failure these exist to prevent is not a crash. It is a report that still
reads correctly and describes a run that no longer exists: `test_results.md`
quoting six labelled waves against a minimum of eight, from a one-day horizon,
while the README discusses the seven-day target. Nothing errors, nothing is
obviously wrong on the page, and a reader has no way to tell which of the two
files is stale.

So the fix is a header that pins each file to a horizon, a snapshot, a panel
hash, a commit and a real/synthetic flag — and these tests keep it there.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from src.models import provenance

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports"

#: Reports that legitimately carry no single provenance block, and why. Both are
#: decisions rather than omissions, which is why they are named here instead of
#: being skipped by a pattern.
WITHOUT_PROVENANCE = {
    # A history spanning many commits and snapshots, one row per run, each row
    # already carrying the code and data it ran on. A single header would have to
    # pick one of them and would misdescribe every other row.
    "depth_ledger.md": "a multi-run history with per-row provenance",
    # Hand-written, and dated in its own opening paragraph. Nothing generates it,
    # so nothing can stamp it.
    "feature_hypotheses.md": "hand-written, not generated",
}


def _provenance() -> provenance.Provenance:
    return provenance.Provenance(
        git_sha="0123456789abcdef",
        git_branch="main",
        git_dirty=False,
        dataset=provenance.REAL,
        panel_path="data/processed/features/job_days_h7_calendar.parquet",
        panel_sha256="fedcba9876543210",
        panel_rows=10_355,
        snapshot_date="2026-09-08",
    )


# --- the block itself -------------------------------------------------------


def test_the_block_names_the_horizon_snapshot_revision_and_whether_it_is_real():
    """The four questions a stale report cannot answer about itself."""
    rendered = "\n".join(
        provenance.header(_provenance(), "python -m src.models.evaluate", "H=7 (calendar basis)")
    )
    assert "H=7 (calendar basis)" in rendered, "no horizon"
    assert "2026-09-08" in rendered, "no snapshot"
    assert "fedcba987654" in rendered, "no panel hash"
    assert "012345678" in rendered, "no code revision"
    assert "**real**" in rendered, "does not say whether this is real or synthetic"


def test_a_synthetic_run_is_marked_as_one():
    """The whole point of the flag: a rehearsal must never read as a result."""
    synthetic = provenance.Provenance(
        git_sha="abc",
        git_branch="main",
        git_dirty=False,
        dataset=provenance.SYNTHETIC,
        panel_path="tests/panels.py",
        panel_sha256="deadbeef",
        panel_rows=360,
        snapshot_date=None,
    )
    rendered = "\n".join(provenance.header(synthetic, "python -m src.models.freeze"))
    assert "**synthetic**" in rendered
    assert "**real**" not in rendered


def test_a_report_with_no_provenance_says_so_rather_than_leaving_a_blank():
    """A silent omission reads as 'this describes the current data'. It may not."""
    rendered = "\n".join(provenance.header(None, "python -m src.data.profile"))
    assert "not recorded" in rendered


def test_a_dirty_tree_is_reported_rather_than_hidden():
    """`provenance.py` logs dirty rather than preventing it; the report must show it."""
    dirty = provenance.Provenance(
        git_sha="abc1234567",
        git_branch="wip",
        git_dirty=True,
        dataset=provenance.REAL,
        panel_path="p.parquet",
        panel_sha256="f00d",
        panel_rows=1,
        snapshot_date="2026-09-08",
    )
    assert "dirty tree" in "\n".join(provenance.header(dirty, "x"))


def test_the_header_has_no_wall_clock_so_regenerating_an_unchanged_run_is_a_no_op():
    """A generated-at line would put a diff in every report on every run.

    A file whose diff is always noise is a file nobody reads the diff of, which
    is precisely how a stale report survives review. The snapshot and the commit
    are the versions that mean something.
    """
    first = provenance.header(_provenance(), "cmd", "H=7")
    second = provenance.header(_provenance(), "cmd", "H=7")
    assert first == second


# --- the committed reports --------------------------------------------------


@pytest.mark.parametrize(
    "report", sorted(path.name for path in REPORTS.glob("*.md")), ids=lambda name: name
)
def test_every_generated_report_identifies_its_provenance(report: str):
    body = (REPORTS / report).read_text()
    if report in WITHOUT_PROVENANCE:
        assert "| Generated by |" not in body, (
            f"{report} is listed as having no provenance block ({WITHOUT_PROVENANCE[report]}) "
            "but now has one — remove it from WITHOUT_PROVENANCE"
        )
        return
    assert "| Generated by |" in body, (
        f"{report} carries no provenance block, so a reader cannot tell which horizon, "
        "snapshot or commit it describes. Regenerate it, or add it to WITHOUT_PROVENANCE "
        "with the reason."
    )
    assert "| Data |" in body and "| Code |" in body, f"{report} has a partial provenance block"


# --- the narrative that used to carry last week's numbers -------------------


def _table(honest: float, leaked: float, ece_leaked: float, ece_other: float) -> pd.DataFrame:
    return pd.DataFrame(
        {
            "run": [
                "05-xgboost_engineered",
                "06-xgboost_leaky",
                "07-xgboost_leak_removed",
                "03-random_forest",
            ],
            "val_pr_auc": [honest, leaked, honest, 0.2],
            "val_ece": [ece_other, ece_leaked, ece_other, ece_other],
        }
    )


def test_the_leak_narrative_takes_its_numbers_from_the_run_it_sits_under():
    """The defect this closes: prose asserting +0.6471 under a table showing +0.7186.

    Two numbers for one quantity in one file is worse than either alone, because
    a reader has no way to tell which is the stale one.
    """
    from src.models.experiments import in_my_own_words

    prose = in_my_own_words(_table(honest=0.1000, leaked=0.9000, ece_leaked=0.02, ece_other=0.05))
    assert "+0.8000" in prose, "the inflation is not the run's"
    assert "0.1000" in prose, "the honest score is not the run's"
    assert "0.9000" in prose, "the leaked score is not the run's"
    for stale in ("0.6471", "0.8385", "0.1915", "0.0377", "0.1902"):
        assert stale not in prose, f"{stale} is hardcoded from an older synthetic replay"


def test_the_calibration_superlative_is_checked_against_the_table_not_asserted():
    """Correct numerals in a now-false sentence is the subtler version of the bug.

    On the synthetic replay the leaky run really was the best-calibrated in the
    table, which is the sharpest form of the point. On another panel it may not
    be, and a sentence that kept claiming it would be refuted by the table three
    lines above it.
    """
    from src.models.experiments import in_my_own_words

    best = in_my_own_words(_table(0.1, 0.9, ece_leaked=0.01, ece_other=0.05))
    assert "best calibration in the whole table" in best

    not_best = in_my_own_words(_table(0.1, 0.9, ece_leaked=0.05, ece_other=0.01))
    assert "best calibration in the whole table" not in not_best
    assert "as well calibrated as the honest run" in not_best
