"""What a run needs to be reproducible: the code version and the data version.

Every run logs its params and its metrics, and then two things that are easy to
leave out: **the dataset version and the git SHA**. Those two matter more than
they look, because they are the ones that cannot be recovered afterwards. A metric with no
dataset version is not comparable to anything — the scraper adds a wave a day,
so "PR-AUC 0.31" without a snapshot is a number about an unknown quantity of
data. A metric with no commit is not reproducible — the pipeline that produced
it has since been edited.

**`dirty` is logged, not prevented — except at the freeze.** Refusing to run
on a dirty tree would be the wrong trade for experiments: most runs happen
mid-edit, and a driver that will not run until you commit is a driver you stop
using. Recording it means a run tagged `git_dirty=true` is understood as
provisional, which is the honest status. The one step where provisional is
not acceptable is the one that opens the held-out block and writes the
artifact that ships: a SHA cannot reproduce a result if uncommitted source
changes affected the run, so `freeze` refuses on a real panel unless
`worktree_is_clean()` (decided 2026-09-11, `design.md` §16).
"""

from __future__ import annotations

import hashlib
import json
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path

#: Written into every run so a reader can tell a real result from a rehearsal
#: on the synthetic panel. Not cosmetic: the synthetic runs exist precisely to
#: exercise machinery that the real panel is still too shallow to drive, and a
#: history that mixed the two without saying so would be worse than no history.
REAL, SYNTHETIC = "real", "synthetic"


def _git(*args: str) -> str | None:
    try:
        return subprocess.run(
            ["git", *args], capture_output=True, text=True, check=True
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):  # pragma: no cover
        return None


@dataclass(frozen=True)
class Provenance:
    """Everything needed to say *which code, on which data*."""

    git_sha: str | None
    git_branch: str | None
    git_dirty: bool
    dataset: str
    panel_path: str
    panel_sha256: str | None
    panel_rows: int
    snapshot_date: str | None

    def as_tags(self) -> dict[str, str]:
        return {key: str(value) for key, value in asdict(self).items()}


#: The header every generated report opens with. One block, one shape, so that
#: "which panel, which horizon, which commit, real or synthetic" is answered in
#: the same place on every file rather than in a different sentence on each.
#:
#: **Deliberately no wall-clock timestamp.** A generated-at line changes on every
#: run, so every regeneration would produce a diff even when nothing moved, and a
#: report whose diff is always noise is a report nobody reads the diff of. The
#: snapshot date and the commit are the versions that mean something; if both are
#: unchanged the file should be unchanged, and that is a property worth having.
#:
#: **`dirty tree` on a report is weak signal, and knowing why matters.** The flag
#: describes the working tree at the moment the report was written — and writing
#: reports is itself a modification, so a batch regeneration dirties the tree for
#: every file after the first. Read it on a *run* as "this was provisional"; read
#: it on a report as "regenerated in a tree that had edits", which is the ordinary
#: case. The commit beside it is the load-bearing half.
def header(
    prov: Provenance | None,
    generator: str,
    horizon: str | None = None,
    extra: dict[str, str] | None = None,
) -> list[str]:
    """The provenance block, as markdown lines.

    Renders what it has. A missing `Provenance` gives the generator line and an
    explicit note, rather than an inviting blank — a report that does not say
    which data it describes should say *that*, since the alternative is a reader
    assuming it describes the current one.
    """
    rows = [f"| Generated by | `{generator}` |"]
    if horizon:
        rows.append(f"| Horizon | {horizon} |")

    if prov is None:
        rows.append(
            "| Provenance | **not recorded** — this report cannot say which "
            "panel or commit produced it |"
        )
    else:
        dataset = "**real**" if prov.dataset == REAL else f"**{prov.dataset}**"
        snapshot = f" · snapshot `{prov.snapshot_date}`" if prov.snapshot_date else ""
        rows.append(f"| Data | {dataset}{snapshot} · `{prov.panel_path}` |")

        digest = f"`{prov.panel_sha256[:12]}…`" if prov.panel_sha256 else "_unhashed_"
        rows.append(f"| Panel | {prov.panel_rows:,} rows · sha256 {digest} |")

        if prov.git_sha:
            state = "dirty tree" if prov.git_dirty else "clean"
            branch = f" on `{prov.git_branch}`" if prov.git_branch else ""
            rows.append(f"| Code | `{prov.git_sha[:9]}`{branch} ({state}) |")
        else:
            rows.append("| Code | **revision unknown** — not a git checkout |")

    for key, value in (extra or {}).items():
        rows.append(f"| {key} | {value} |")

    return ["| | |", "|---|---|", *rows, "", "_Regenerate rather than edit._", ""]


def sha256_of(path: Path, chunk_size: int = 1 << 20) -> str:
    """Content hash of a file. Same rule as `src/data/snapshot.py`."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _snapshot_date_for(panel_path: Path, raw_root: Path = Path("data/raw")) -> str | None:
    """The snapshot a report is about.

    A report that reads a specific pinned snapshot — the dated data profiles
    do, by manifest path — is about *that* snapshot, not the newest one on
    disk: until 2026-09-12 the profile of 2026-09-04, regenerated later, said
    it described the 2026-09-12 snapshot. So a path under `data/raw/<date>/`
    names its own snapshot, and everything else (a derived panel) is about
    the newest, which is the one it was built from.
    """
    try:
        parts = Path(panel_path).resolve().relative_to(raw_root.resolve()).parts
    except ValueError:
        return _snapshot_date(raw_root)
    if parts:
        manifest = raw_root / parts[0] / "manifest.json"
        try:
            return str(json.loads(manifest.read_text())["snapshot_date"])
        except (OSError, ValueError, KeyError):
            return parts[0]
    return _snapshot_date(raw_root)


def _snapshot_date(raw_root: Path = Path("data/raw")) -> str | None:
    """The date of the most recent pinned snapshot, if one exists.

    Read from the manifest rather than the directory name, because the
    directory name is a label a human typed and the manifest is what
    `src/data/snapshot.py` actually wrote.
    """
    manifests = sorted(raw_root.glob("*/manifest.json"))
    if not manifests:
        return None
    try:
        return str(json.loads(manifests[-1].read_text())["snapshot_date"])
    except (OSError, ValueError, KeyError):  # pragma: no cover
        return None


#: The dependency lock whose hash travels on the artifact. A SHA pins the
#: source; this pins what the source ran against — every package, hashed, as
#: `uv sync --locked` installs it locally, in CI and in the serving image. It
#: is committed, which is what makes the hash mean something: until 2026-09-11
#: the file was gitignored, so the hash named a resolution nobody else could
#: fetch, and the artifact's "dependencies" line was a promise with no object
#: behind it. Anchored to the repository root rather than the working
#: directory, so a freeze run from anywhere hashes the same file.
LOCK_FILE = Path(__file__).resolve().parents[2] / "uv.lock"


def lock_sha256(path: Path = LOCK_FILE) -> str | None:
    """The lock's sha256, or None outside a checkout that has one."""
    return sha256_of(path) if path.exists() else None


def period(frame, column: str = "t") -> dict[str, str | int | None]:
    """The first and last prediction instant a block covers, as dates.

    Every claim this project makes is about a period, and a claim without one
    reads as a claim about all time. A one-month test block validates a
    one-month period — weekday, season, holiday, hiring-cycle and board-policy
    effects longer than that are not demonstrated by it, and the depth ledger
    across successive snapshots is where they would show, or not. So the
    period travels with the number: on the artifact, in the report header, on
    `/health`.
    """
    if frame is None or len(frame) == 0:
        return {"start": None, "end": None, "days": 0}
    stamps = frame[column]
    start, end = stamps.min(), stamps.max()
    return {
        "start": str(start.date()),
        "end": str(end.date()),
        "days": int((end.normalize() - start.normalize()).days) + 1,
    }


def source_is_dirty() -> bool:
    """Is anything *other than a generated report* uncommitted?

    What a report's `Code` row claims is that the source at that SHA, on that
    snapshot, produced it. Regenerating the reports in a batch writes twenty
    files under `reports/` before any is committed, and counting those as
    dirt made every file after the first say `dirty tree` about itself — a
    header that was noise on the one day it mattered most (2026-09-12: every
    committed report said it). So a report's dirtiness excludes `reports/`:
    the outputs of the run are not inputs to it. `worktree_is_clean`, which
    gates the freeze, stays strict — there the reports must be committed too,
    because they are the evidence the artifact is read against.
    """
    return bool(_git("status", "--porcelain", "--", ".", ":!reports"))


def worktree_is_clean() -> bool:
    """Is there anything uncommitted — tracked or untracked — in the tree?

    `git status --porcelain` is empty exactly when the SHA describes what ran.
    Untracked files count: a new module the run imported is as unreproducible
    as an edited one. Outside a git checkout the answer is False, because
    "no repository" is not "clean".
    """
    try:
        return _git("status", "--porcelain") == "" and _git("rev-parse", "HEAD") != ""
    except Exception:  # pragma: no cover - git absent
        return False


def collect(panel_path: Path, n_rows: int, dataset: str = REAL) -> Provenance:
    """Describe the current code and data.

    The panel is hashed rather than named, because `data/processed/` is
    regenerable and its filename is stable across regenerations: two runs
    against `job_days_h1_calendar.parquet` a week apart are runs against
    different data with the same path. The hash is what distinguishes them.
    """
    return Provenance(
        git_sha=_git("rev-parse", "HEAD"),
        git_branch=_git("rev-parse", "--abbrev-ref", "HEAD"),
        git_dirty=source_is_dirty(),
        dataset=dataset,
        panel_path=str(panel_path),
        panel_sha256=sha256_of(panel_path) if panel_path.exists() else None,
        panel_rows=int(n_rows),
        snapshot_date=_snapshot_date_for(panel_path),
    )
