"""What a run needs to be reproducible: the code version and the data version.

Every run logs its params and its metrics, and then two things that are easy to
leave out: **the dataset version and the git SHA**. Those two matter more than
they look, because they are the ones that cannot be recovered afterwards. A metric with no
dataset version is not comparable to anything — the scraper adds a wave a day,
so "PR-AUC 0.31" without a snapshot is a number about an unknown quantity of
data. A metric with no commit is not reproducible — the pipeline that produced
it has since been edited.

**`dirty` is logged, not prevented — except at the freeze.** Refusing to run
on a dirty tree would be the wrong trade for experiments: most runs happen
mid-edit, and a driver that will not run until you commit is a driver you stop
using. Recording it means a run tagged `git_dirty=true` is understood as
provisional, which is the honest status. The one step where provisional is
not acceptable is the one that opens the held-out block and writes the
artifact that ships: a SHA cannot reproduce a result if uncommitted source
changes affected the run, so `freeze` refuses on a real panel unless
`worktree_is_clean()` (decided 2026-09-11, `design.md` §16).
"""

from __future__ import annotations

import hashlib
import json
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path

#: Written into every run so a reader can tell a real result from a rehearsal
#: on the synthetic panel. Not cosmetic: the synthetic runs exist precisely to
#: exercise machinery that the real panel is still too shallow to drive, and a
#: history that mixed the two without saying so would be worse than no history.
REAL, SYNTHETIC = "real", "synthetic"


def _git(*args: str) -> str | None:
    try:
        return subprocess.run(
            ["git", *args], capture_output=True, text=True, check=True
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):  # pragma: no cover
        return None


@dataclass(frozen=True)
class Provenance:
    """Everything needed to say *which code, on which data*."""

    git_sha: str | None
    git_branch: str | None
    git_dirty: bool
    dataset: str
    panel_path: str
    panel_sha256: str | None
    panel_rows: int
    snapshot_date: str | None

    def as_tags(self) -> dict[str, str]:
        return {key: str(value) for key, value in asdict(self).items()}


#: The header every generated report opens with. One block, one shape, so that
#: "which panel, which horizon, which commit, real or synthetic" is answered in
#: the same place on every file rather than in a different sentence on each.
#:
#: **Deliberately no wall-clock timestamp.** A generated-at line changes on every
#: run, so every regeneration would produce a diff even when nothing moved, and a
#: report whose diff is always noise is a report nobody reads the diff of. The
#: snapshot date and the commit are the versions that mean something; if both are
#: unchanged the file should be unchanged, and that is a property worth having.
#:
#: **`dirty tree` on a report is weak signal, and knowing why matters.** The flag
#: describes the working tree at the moment the report was written — and writing
#: reports is itself a modification, so a batch regeneration dirties the tree for
#: every file after the first. Read it on a *run* as "this was provisional"; read
#: it on a report as "regenerated in a tree that had edits", which is the ordinary
#: case. The commit beside it is the load-bearing half.
def header(
    prov: Provenance | None,
    generator: str,
    horizon: str | None = None,
    extra: dict[str, str] | None = None,
) -> list[str]:
    """The provenance block, as markdown lines.

    Renders what it has. A missing `Provenance` gives the generator line and an
    explicit note, rather than an inviting blank — a report that does not say
    which data it describes should say *that*, since the alternative is a reader
    assuming it describes the current one.
    """
    rows = [f"| Generated by | `{generator}` |"]
    if horizon:
        rows.append(f"| Horizon | {horizon} |")

    if prov is None:
        rows.append(
            "| Provenance | **not recorded** — this report cannot say which "
            "panel or commit produced it |"
        )
    else:
        dataset = "**real**" if prov.dataset == REAL else f"**{prov.dataset}**"
        snapshot = f" · snapshot `{prov.snapshot_date}`" if prov.snapshot_date else ""
        rows.append(f"| Data | {dataset}{snapshot} · `{prov.panel_path}` |")

        digest = f"`{prov.panel_sha256[:12]}…`" if prov.panel_sha256 else "_unhashed_"
        rows.append(f"| Panel | {prov.panel_rows:,} rows · sha256 {digest} |")

        if prov.git_sha:
            state = "dirty tree" if prov.git_dirty else "clean"
            branch = f" on `{prov.git_branch}`" if prov.git_branch else ""
            rows.append(f"| Code | `{prov.git_sha[:9]}`{branch} ({state}) |")
        else:
            rows.append("| Code | **revision unknown** — not a git checkout |")

    for key, value in (extra or {}).items():
        rows.append(f"| {key} | {value} |")

    return ["| | |", "|---|---|", *rows, "", "_Regenerate rather than edit._", ""]


def sha256_of(path: Path, chunk_size: int = 1 << 20) -> str:
    """Content hash of a file. Same rule as `src/data/snapshot.py`."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _snapshot_date(raw_root: Path = Path("data/raw")) -> str | None:
    """The date of the most recent pinned snapshot, if one exists.

    Read from the manifest rather than the directory name, because the
    directory name is a label a human typed and the manifest is what
    `src/data/snapshot.py` actually wrote.
    """
    manifests = sorted(raw_root.glob("*/manifest.json"))
    if not manifests:
        return None
    try:
        return str(json.loads(manifests[-1].read_text())["snapshot_date"])
    except (OSError, ValueError, KeyError):  # pragma: no cover
        return None


#: The dependency lock whose hash travels on the artifact. A SHA pins the
#: source; this pins what the source ran against.
LOCK_FILE = Path("uv.lock")


def lock_sha256(path: Path = LOCK_FILE) -> str | None:
    return sha256_of(path) if path.exists() else None


def worktree_is_clean() -> bool:
    """Is there anything uncommitted — tracked or untracked — in the tree?

    `git status --porcelain` is empty exactly when the SHA describes what ran.
    Untracked files count: a new module the run imported is as unreproducible
    as an edited one. Outside a git checkout the answer is False, because
    "no repository" is not "clean".
    """
    try:
        return _git("status", "--porcelain") == "" and _git("rev-parse", "HEAD") != ""
    except Exception:  # pragma: no cover - git absent
        return False


def collect(panel_path: Path, n_rows: int, dataset: str = REAL) -> Provenance:
    """Describe the current code and data.

    The panel is hashed rather than named, because `data/processed/` is
    regenerable and its filename is stable across regenerations: two runs
    against `job_days_h1_calendar.parquet` a week apart are runs against
    different data with the same path. The hash is what distinguishes them.
    """
    return Provenance(
        git_sha=_git("rev-parse", "HEAD"),
        git_branch=_git("rev-parse", "--abbrev-ref", "HEAD"),
        git_dirty=bool(_git("status", "--porcelain")),
        dataset=dataset,
        panel_path=str(panel_path),
        panel_sha256=sha256_of(panel_path) if panel_path.exists() else None,
        panel_rows=int(n_rows),
        snapshot_date=_snapshot_date(),
    )
